"""rename department

Revision ID: 697f4789cb4c
Revises: b891ff4145de
Create Date: 2025-06-11 19:21:22.183501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697f4789cb4c'
down_revision = 'b891ff4145de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
