"""rename address

Revision ID: 7b6387b8e2a9
Revises: 697f4789cb4c
Create Date: 2025-06-11 19:24:32.174922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6387b8e2a9'
down_revision = '697f4789cb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address', new_column_name= 'location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')


    # ### end Alembic commands ###
